/**
 * GENERATED by `scripts/render-podium.mjs`. Do not edit.
 *
 * Where `public/podium/blocks.png`'s three blocks are, as fractions of the
 * image with the origin at its top left. `front` is a block's face, which is
 * an exact rectangle because the render's camera is off-axis; `top` is the
 * centre of its top face, where the mark stands; `mark` is that mark's
 * diameter as a fraction of the image's width.
 *
 * Re-run the script after changing any block's size, the camera, or the view.
 */

export type BlockAnchor = {
  front: { x: number; y: number; w: number; h: number }
  top: { x: number; y: number }
  mark: number
}

export const BLOCK_IMAGE = { src: '/podium/blocks.png', width: 1920, height: 1695 } as const

export const BLOCKS: Record<number, BlockAnchor> = {
  "1": {
    "front": {
      "x": 0.32031,
      "y": 0.33628,
      "w": 0.35938,
      "h": 0.63717
    },
    "top": {
      "x": 0.5,
      "y": 0.27614
    },
    "mark": 0.19531
  },
  "2": {
    "front": {
      "x": 0.02656,
      "y": 0.46903,
      "w": 0.27344,
      "h": 0.50442
    },
    "top": {
      "x": 0.19262,
      "y": 0.39731
    },
    "mark": 0.14844
  },
  "3": {
    "front": {
      "x": 0.7,
      "y": 0.57522,
      "w": 0.27344,
      "h": 0.39823
    },
    "top": {
      "x": 0.80738,
      "y": 0.49425
    },
    "mark": 0.14844
  }
}
